[package]
name = "n3ds-remote-play-common"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3"
bitflags = { version = "2.4", features = ["serde"]}
serde = { version = "1.0", features = ["derive"] }
